# Lab | Web Scraping

Welcome to the "Books to Scrape" Web Scraping Adventure Lab!

**Objective**

In this lab, we will embark on a mission to unearth valuable insights from the data available on Books to Scrape, an online platform showcasing a wide variety of books. As data analyst, you have been tasked with scraping a specific subset of book data from Books to Scrape to assist publishing companies in understanding the landscape of highly-rated books across different genres. Your insights will help shape future book marketing strategies and publishing decisions.

**Background**

In a world where data has become the new currency, businesses are leveraging big data to make informed decisions that drive success and profitability. The publishing industry, much like others, utilizes data analytics to understand market trends, reader preferences, and the performance of books based on factors such as genre, author, and ratings. Books to Scrape serves as a rich source of such data, offering detailed information about a diverse range of books, making it an ideal platform for extracting insights to aid in informed decision-making within the literary world.

**Task**

Your task is to create a Python script using BeautifulSoup and pandas to scrape Books to Scrape book data, focusing on book ratings and genres. The script should be able to filter books with ratings above a certain threshold and in specific genres. Additionally, the script should structure the scraped data in a tabular format using pandas for further analysis.

**Expected Outcome**

A function named `scrape_books` that takes two parameters: `min_rating` and `max_price`. The function should scrape book data from the "Books to Scrape" website and return a `pandas` DataFrame with the following columns:

**Expected Outcome**

- A function named `scrape_books` that takes two parameters: `min_rating` and `max_price`.
- The function should return a DataFrame with the following columns:
  - **UPC**: The Universal Product Code (UPC) of the book.
  - **Title**: The title of the book.
  - **Price (£)**: The price of the book in pounds.
  - **Rating**: The rating of the book (1-5 stars).
  - **Genre**: The genre of the book.
  - **Availability**: Whether the book is in stock or not.
  - **Description**: A brief description or product description of the book (if available).
  
You will execute this script to scrape data for books with a minimum rating of `4.0 and above` and a maximum price of `£20`. 

Remember to experiment with different ratings and prices to ensure your code is versatile and can handle various searches effectively!

**Resources**

- [Beautiful Soup Documentation](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)
- [Pandas Documentation](https://pandas.pydata.org/pandas-docs/stable/index.html)
- [Books to Scrape](https://books.toscrape.com/)

**Hint**

Your first mission is to familiarize yourself with the **Books to Scrape** website. Navigate to [Books to Scrape](http://books.toscrape.com/) and explore the available books to understand their layout and structure. 

Next, think about how you can set parameters for your data extraction:

- **Minimum Rating**: Focus on books with a rating of 4.0 and above.
- **Maximum Price**: Filter for books priced up to £20.

After reviewing the site, you can construct a plan for scraping relevant data. Pay attention to the details displayed for each book, including the title, price, rating, and availability. This will help you identify the correct HTML elements to target with your scraping script.

Make sure to build your scraping URL and logic based on the patterns you observe in the HTML structure of the book listings!


---

**Best of luck! Immerse yourself in the world of books, and may the data be with you!**

**Important Note**:

In the fast-changing online world, websites often update and change their structures. When you try this lab, the **Books to Scrape** website might differ from what you expect.

If you encounter issues due to these changes, like new rules or obstacles preventing data extraction, don’t worry! Get creative.

You can choose another website that interests you and is suitable for scraping data. Options like Wikipedia, The New York Times, or even library databases are great alternatives. The main goal remains the same: extract useful data and enhance your web scraping skills while exploring a source of information you enjoy. This is your opportunity to practice and adapt to different web environments!

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [ ]:
!python -m pip install pandas

In [ ]:
!pip install requests beautifulsoup4 pandas

In [ ]:
import pandas as pd
print(pd.__version__)

In [ ]:
!pip install pandas

In [ ]:
import pandas as pd

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [ ]:
url = "https://books.toscrape.com/"
response = requests.get(url)
html = response.text

In [ ]:
soup = BeautifulSoup(html, "html.parser")

In [ ]:
books = soup.find_all("article", class_="product_pod")

In [ ]:
data = []

for book in books:
    title = book.h3.a["title"]
    price = book.find("p", class_="price_color").text
    rating = book.p["class"][1]  # ej: "Three", "Five", etc

    data.append({
        "title": title,
        "price": price,
        "rating": rating
    })

In [ ]:
df = pd.DataFrame(data)
df.head()

In [ ]:
df_filtered = df[df["price"] < 30]

In [ ]:
df["price"] = df["price"].str.replace("£", "")

In [ ]:
df["price"] = df["price"].astype(float)

In [ ]:
df["price"] = df["price"].str.replace("Â", "")
df["price"] = df["price"].str.replace("£", "")

In [ ]:
df["price"] = df["price"].astype(float)

In [ ]:
df_filtered = df[df["price"] < 30]
df_filtered

In [ ]:
def scrape_books(min_rating, max_price):

In [ ]:
def scrape_books

In [ ]:
def scrape_books(min_rating, max_price):

    url = "https://books.toscrape.com/"
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")

    books = soup.find_all("article", class_="product_pod")

    data = []

    for book in books:
        title = book.h3.a["title"]
        price = book.find("p", class_="price_color").text
        rating = book.p["class"][1]

        # limpiar precio
        price = price.replace("£", "").replace("Â", "")
        price = float(price)

        data.append({
            "title": title,
            "price": price,
            "rating": rating
        })

    df = pd.DataFrame(data)

    # filtrar por precio
    df = df[df["price"] <= max_price]

    return df

In [ ]:
df_result = scrape_books(4, 20)
df_result

In [ ]:
rating_map = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

df["rating"] = df["rating"].map(rating_map)

df = df[df["rating"] >= min_rating]

In [ ]:
def scrape_books(min_rating, max_price):

    url = "https://books.toscrape.com/"
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")

    books = soup.find_all("article", class_="product_pod")

    data = []

    rating_map = {
        "One": 1,
        "Two": 2,
        "Three": 3,
        "Four": 4,
        "Five": 5
    }

    for book in books:
        title = book.h3.a["title"]
        price = book.find("p", class_="price_color").text
        rating = book.p["class"][1]

        price = price.replace("£", "").replace("Â", "")
        price = float(price)

        rating = rating_map[rating]

        data.append({
            "title": title,
            "price": price,
            "rating": rating
        })

    df = pd.DataFrame(data)

    df = df[df["price"] <= max_price]
    df = df[df["rating"] >= min_rating]

    return df

In [ ]:
scrape_books(4, 20)

In [ ]:
df = scrape_books(4, 20)
df

In [ ]:
df_result = scrape_books(4, 20)
df_result

In [ ]:
link = book.h3.a["href"]
full_url = "https://books.toscrape.com/catalogue/" + link.replace("../", "")

In [ ]:
book_page = requests.get(full_url)
book_soup = BeautifulSoup(book_page.text, "html.parser")

In [ ]:
upc = book_soup.find("th", text="UPC").find_next_sibling("td").text
availability = book_soup.find("th", text="Availability").find_next_sibling("td").text
description = book_soup.find("div", id="product_description")
description = description.find_next("p").text if description else ""

In [ ]:
table = book_soup.find("table", class_="table table-striped")

rows = table.find_all("tr")

book_info = {}

for row in rows:
    key = row.find("th").text
    value = row.find("td").text
    book_info[key] = value

In [ ]:
print(book_soup.prettify()[:1000])

In [ ]:
print(book_soup)

In [ ]:
base_url = "https://books.toscrape.com/catalogue/"

link = book.h3.a["href"]
full_url = base_url + link.replace("../", "")

In [ ]:
from urllib.parse import urljoin

base_url = "https://books.toscrape.com/catalogue/"
full_url = urljoin(base_url, book.h3.a["href"])

In [ ]:
print(full_url)

In [ ]:
from urllib.parse import urljoin

base_url = "https://books.toscrape.com/catalogue/"

href = book.h3.a["href"]
full_url = urljoin(base_url, href)

In [ ]:
book_response = requests.get(full_url)
book_soup = BeautifulSoup(book_response.text, "html.parser")

In [ ]:
table = book_soup.find("table", class_="table table-striped")

rows = table.find_all("tr")

book_info = {}

for row in rows:
    key = row.find("th").text
    value = row.find("td").text
    book_info[key] = value

In [ ]:
print(full_url)
print(book_response.status_code)

In [ ]:
base_url = "https://books.toscrape.com/"

In [ ]:
from urllib.parse import urljoin

href = book.h3.a["href"]
full_url = urljoin(base_url, href)

In [ ]:
print(book_response.status_code)

In [ ]:
href = book.h3.a["href"]
print(href)

In [ ]:
from urllib.parse import urljoin

base_url = "https://books.toscrape.com/"

href = book.h3.a["href"]
full_url = urljoin(base_url, href)

print(full_url)

In [ ]:
print(full_url)
print(requests.get(full_url).status_code)

In [ ]:
print(full_url)

In [ ]:
book_response = requests.get(full_url)
book_soup = BeautifulSoup(book_response.text, "html.parser")

In [ ]:
table = book_soup.find("table", class_="table table-striped")

rows = table.find_all("tr")

book_info = {}

for row in rows:
    key = row.find("th").text
    value = row.find("td").text
    book_info[key] = value

In [ ]:
desc_tag = book_soup.find("div", id="product_description")
description = desc_tag.find_next("p").text if desc_tag else ""

In [ ]:
genre = book_soup.find_all("li")[2].text.strip()

In [ ]:
rating = book.p["class"][1]

In [ ]:
data.append({
    "UPC": book_info.get("UPC"),
    "Title": book.h3.a["title"],
    "Price": book.find("p", class_="price_color").text,
    "Rating": rating,
    "Genre": genre,
    "Availability": book_info.get("Availability"),
    "Description": description
})

In [ ]:
df = pd.DataFrame(data)
df.head()

In [ ]:
df["Price"] = df["Price"].str.replace("£", "").astype(float)

rating_map = {"One":1,"Two":2,"Three":3,"Four":4,"Five":5}
df["Rating"] = df["Rating"].map(rating_map)

df = df[(df["Rating"] >= min_rating) & (df["Price"] <= max_price)]

In [ ]:
df["Price"] = (
    df["Price"]
    .str.replace("Â", "", regex=False)
    .str.replace("£", "", regex=False)
    .str.strip()
    .astype(float)
)

In [ ]:
df = df[(df["Rating"] >= min_rating) & (df["Price"] <= max_price)]

In [ ]:
df = scrape_books(4, 20)
df

In [ ]:
df = df[(df["Rating"] >= 4) & (df["Price"] <= 20)]

In [ ]:
print(df.columns)

In [ ]:
df = df[(df["rating"] >= 4) & (df["price"] <= 20)]
df

In [ ]:
df["price"] = df["price"].str.replace("£", "").str.replace("Â", "").astype(float)

rating_map = {"One":1,"Two":2,"Three":3,"Four":4,"Five":5}
df["rating"] = df["rating"].map(rating_map)

In [ ]:
print(df.dtypes)

In [ ]:
# UPC y availability
table = book_soup.find("table", class_="table table-striped")
rows = table.find_all("tr")

book_info = {}
for row in rows:
    key = row.th.text
    value = row.td.text
    book_info[key] = value

upc = book_info.get("UPC", "")
availability = book_info.get("Availability", "")

In [ ]:
desc_section = book_soup.find("div", id="product_description")
if desc_section:
    description = desc_section.find_next("p").text
else:
    description = ""

In [ ]:
breadcrumb = book_soup.find("ul", class_="breadcrumb")
genre = breadcrumb.find_all("li")[2].text.strip()

In [ ]:
data.append({
    "title": title,
    "price": price,
    "rating": rating,
    "upc": upc,
    "availability": availability,
    "description": description,
    "genre": genre
})

In [ ]:
df = scrape_books(4, 20)
df.head()

In [ ]:
def scrape_books(min_rating, max_price):

    import requests
    from bs4 import BeautifulSoup
    import pandas as pd

    base_url = "https://books.toscrape.com/catalogue/page-{}.html"
    data = []

    rating_map = {"One":1,"Two":2,"Three":3,"Four":4,"Five":5}

    for page in range(1, 51):
        url = base_url.format(page)
        response = requests.get(url)
        soup = BeautifulSoup(response.text, "html.parser")

        books = soup.find_all("article", class_="product_pod")

        for book in books:
            title = book.h3.a["title"]
            price = book.find("p", class_="price_color").text
            rating = book.p["class"][1]

            price = price.replace("£", "").replace("Â", "")
            price = float(price)
            rating = rating_map[rating]

            data.append({
                "title": title,
                "price": price,
                "rating": rating
            })

    df = pd.DataFrame(data)

    # filtros
    df = df[(df["price"] <= max_price) & (df["rating"] >= min_rating)]

    return df

In [ ]:
df = scrape_books(4, 20)
df

In [ ]:
df = scrape_books(4, 20)

print(len(df))
df.head()

In [ ]:
rating = rating_map.get(rating, None)

In [ ]:
df = df.dropna()

In [ ]:
df = scrape_books(4, 20)

print(df.shape)
df.head()

In [ ]:
print(df["price"].max())
print(df["rating"].min())

In [ ]:
from urllib.parse import urljoin

base_book_url = "https://books.toscrape.com/catalogue/"

href = book.h3.a["href"]
full_url = urljoin(base_book_url, href)

In [ ]:
book_response = requests.get(full_url, headers={"User-Agent": "Mozilla/5.0"})
book_soup = BeautifulSoup(book_response.text, "html.parser")

In [ ]:
table = book_soup.find("table", class_="table table-striped")

book_info = {}
if table:
    rows = table.find_all("tr")
    for row in rows:
        key = row.th.text
        value = row.td.text
        book_info[key] = value

upc = book_info.get("UPC", "")
availability = book_info.get("Availability", "")

In [ ]:
desc_section = book_soup.find("div", id="product_description")

if desc_section:
    description = desc_section.find_next("p").text
else:
    description = ""

In [ ]:
breadcrumb = book_soup.find("ul", class_="breadcrumb")
genre = breadcrumb.find_all("li")[2].text.strip()

In [ ]:
if breadcrumb:
    genre = breadcrumb.find_all("li")[2].text.strip()
else:
    genre = ""

In [ ]:
# GENRE
breadcrumb = book_soup.find("ul", class_="breadcrumb")
if breadcrumb:
    genre = breadcrumb.find_all("li")[2].text.strip()
else:
    genre = ""

# TABLE (UPC + availability)
table = book_soup.find("table", class_="table table-striped")

book_info = {}
if table:
    rows = table.find_all("tr")
    for row in rows:
        key = row.th.text
        value = row.td.text
        book_info[key] = value

upc = book_info.get("UPC", "")
availability = book_info.get("Availability", "")

# DESCRIPTION
desc_section = book_soup.find("div", id="product_description")
if desc_section:
    description = desc_section.find_next("p").text
else:
    description = ""

In [ ]:
book_response = requests.get(full_url, headers={"User-Agent": "Mozilla/5.0"})

if book_response.status_code != 200:
    continue

In [ ]:
from urllib.parse import urljoin
import requests
from bs4 import BeautifulSoup
import pandas as pd

def scrape_books(min_rating, max_price):

    base_url = "https://books.toscrape.com/"
    page_url = "https://books.toscrape.com/catalogue/page-{}.html"

    data = []

    rating_map = {"One":1,"Two":2,"Three":3,"Four":4,"Five":5}

    for page in range(1, 51):
        response = requests.get(page_url.format(page))
        soup = BeautifulSoup(response.text, "html.parser")

        books = soup.find_all("article", class_="product_pod")

        for book in books:

            # --- datos básicos ---
            title = book.h3.a["title"]
            price = book.find("p", class_="price_color").text
            rating = book.p["class"][1]

            price = float(price.replace("£", "").replace("Â", ""))
            rating = rating_map[rating]

            # --- entrar al detalle del libro ---
            href = book.h3.a["href"]
            full_url = urljoin(base_url, href)

            book_response = requests.get(full_url)

            if book_response.status_code != 200:
                continue

            book_soup = BeautifulSoup(book_response.text, "html.parser")

            # --- tabla (UPC + availability) ---
            table = book_soup.find("table", class_="table table-striped")
            book_info = {}

            if table:
                for row in table.find_all("tr"):
                    key = row.th.text
                    value = row.td.text
                    book_info[key] = value

            upc = book_info.get("UPC", "")
            availability = book_info.get("Availability", "")

            # --- descripción ---
            desc_section = book_soup.find("div", id="product_description")
            description = desc_section.find_next("p").text if desc_section else ""

            # --- género ---
            breadcrumb = book_soup.find("ul", class_="breadcrumb")
            if breadcrumb:
                genre = breadcrumb.find_all("li")[2].text.strip()
            else:
                genre = ""

            # --- guardar ---
            data.append({
                "UPC": upc,
                "Title": title,
                "Price (£)": price,
                "Rating": rating,
                "Genre": genre,
                "Availability": availability,
                "Description": description
            })

    df = pd.DataFrame(data)

    # filtros finales
    df = df[(df["Rating"] >= min_rating) & (df["Price (£)"] <= max_price)]

    return df

In [ ]:
df = scrape_books(4, 20)

print(df.shape)
df.head()

In [ ]:
df = scrape_books(4, 20)
print(df.shape)
print(df.head())

In [ ]:
df = scrape_books(4, 20)
print(df.head(10))

In [ ]:
df = scrape_books(1, 100)
print(len(df))

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://books.toscrape.com/catalogue/page-1.html"
r = requests.get(url)
soup = BeautifulSoup(r.text, "html.parser")

books = soup.find_all("article", class_="product_pod")

print(len(books))

In [ ]:
print("inicio")
df = scrape_books(4, 20)
print("terminó")
print(df.shape)

In [ ]:
import requests

url = "https://books.toscrape.com/catalogue/page-1.html"
r = requests.get(url)

print(r.status_code)
print("ok")

In [ ]:
print("hola mundo")

In [ ]:
print("reiniciado")

In [ ]:
import requests

r = requests.get("https://books.toscrape.com/")
print(r.status_code)

In [ ]:
df = scrape_books(4, 20)
print(df.shape)
df.head()

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from urllib.parse import urljoin

def scrape_books(min_rating, max_price):

    base_url = "https://books.toscrape.com/"

    page_url = "https://books.toscrape.com/catalogue/page-{}.html"

    data = []

    rating_map = {"One":1,"Two":2,"Three":3,"Four":4,"Five":5}

    for page in range(1, 51):

        response = requests.get(page_url.format(page))
        soup = BeautifulSoup(response.text, "html.parser")

        books = soup.find_all("article", class_="product_pod")

        for book in books:

            title = book.h3.a["title"]
            price = book.find("p", class_="price_color").text
            rating = book.p["class"][1]

            price = float(price.replace("£", "").replace("Â", ""))
            rating = rating_map[rating]

            # detalle libro
            href = book.h3.a["href"]
            full_url = urljoin(base_url, href)

            book_page = requests.get(full_url)
            book_soup = BeautifulSoup(book_page.text, "html.parser")

            table = book_soup.find("table", class_="table table-striped")
            book_info = {}

            if table:
                for row in table.find_all("tr"):
                    book_info[row.th.text] = row.td.text

            description = ""
            desc = book_soup.find("div", id="product_description")
            if desc:
                description = desc.find_next("p").text

            breadcrumb = book_soup.find("ul", class_="breadcrumb")
            genre = breadcrumb.find_all("li")[2].text.strip() if breadcrumb else ""

            data.append({
                "UPC": book_info.get("UPC", ""),
                "Title": title,
                "Price": price,
                "Rating": rating,
                "Genre": genre,
                "Availability": book_info.get("Availability", ""),
                "Description": description
            })

    df = pd.DataFrame(data)

    df = df[(df["Rating"] >= min_rating) & (df["Price"] <= max_price)]

    return df

In [ ]:
df = scrape_books(4, 20)
print(df.shape)
df.head()

In [ ]:
print("funciona")

In [ ]:
print("kernel activo")

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from urllib.parse import urljoin

In [ ]:
def scrape_books(min_rating, max_price):

    import requests
    from bs4 import BeautifulSoup
    import pandas as pd
    from urllib.parse import urljoin

    base_url = "https://books.toscrape.com/"

    page_url = "https://books.toscrape.com/catalogue/page-{}.html"

    data = []

    rating_map = {
        "One": 1,
        "Two": 2,
        "Three": 3,
        "Four": 4,
        "Five": 5
    }

    for page in range(1, 51):

        response = requests.get(page_url.format(page))
        soup = BeautifulSoup(response.text, "html.parser")

        books = soup.find_all("article", class_="product_pod")

        for book in books:

            title = book.h3.a["title"]
            price = book.find("p", class_="price_color").text
            rating = book.p["class"][1]

            price = float(price.replace("£", "").replace("Â", ""))
            rating = rating_map[rating]

            # link detalle
            href = book.h3.a["href"]
            full_url = urljoin(base_url, href)

            book_page = requests.get(full_url)
            book_soup = BeautifulSoup(book_page.text, "html.parser")

            # tabla
            table = book_soup.find("table", class_="table table-striped")
            book_info = {}

            if table:
                for row in table.find_all("tr"):
                    key = row.th.text
                    value = row.td.text
                    book_info[key] = value

            # descripción
            desc = book_soup.find("div", id="product_description")
            description = desc.find_next("p").text if desc else ""

            # género
            breadcrumb = book_soup.find("ul", class_="breadcrumb")
            genre = breadcrumb.find_all("li")[2].text.strip() if breadcrumb else ""

            data.append({
                "UPC": book_info.get("UPC", ""),
                "Title": title,
                "Price": price,
                "Rating": rating,
                "Genre": genre,
                "Availability": book_info.get("Availability", ""),
                "Description": description
            })

    df = pd.DataFrame(data)

    df = df[(df["Rating"] >= min_rating) & (df["Price"] <= max_price)]

    return df

In [ ]:
df = scrape_books(4, 20)
print(df.shape)
df.head()

In [ ]:
print("inicio")

df = scrape_books(4, 20)

print("terminó")
print(df.shape)

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from urllib.parse import urljoin

def scrape_books(min_rating, max_price):

    base_url = "https://books.toscrape.com/"
    page_url = "https://books.toscrape.com/catalogue/page-{}.html"

    data = []

    rating_map = {"One":1,"Two":2,"Three":3,"Four":4,"Five":5}

    headers = {"User-Agent": "Mozilla/5.0"}

    for page in range(1, 10):  # 👈 IMPORTANTE: menos páginas para evitar cuelgue

        r = requests.get(page_url.format(page), headers=headers)
        soup = BeautifulSoup(r.text, "html.parser")

        books = soup.find_all("article", class_="product_pod")

        for book in books:

            title = book.h3.a["title"]
            price = float(book.find("p", class_="price_color").text.replace("£","").replace("Â",""))
            rating = rating_map[book.p["class"][1]]

            if price > max_price or rating < min_rating:
                continue

            href = book.h3.a["href"]
            full_url = urljoin(base_url, href)

            book_page = requests.get(full_url, headers=headers)
            book_soup = BeautifulSoup(book_page.text, "html.parser")

            table = book_soup.find("table", class_="table table-striped")

            info = {}
            if table:
                for row in table.find_all("tr"):
                    info[row.th.text] = row.td.text

            desc = book_soup.find("div", id="product_description")
            description = desc.find_next("p").text if desc else ""

            breadcrumb = book_soup.find("ul", class_="breadcrumb")
            genre = breadcrumb.find_all("li")[2].text.strip() if breadcrumb else ""

            data.append({
                "UPC": info.get("UPC",""),
                "Title": title,
                "Price": price,
                "Rating": rating,
                "Genre": genre,
                "Availability": info.get("Availability",""),
                "Description": description
            })

    return pd.DataFrame(data)

In [ ]:
df = scrape_books(4, 20)
print(df.shape)
df.head()

In [ ]:
href = book.h3.a["href"]
full_url = urljoin(base_url, href)

book_page = requests.get(full_url, headers=headers)
book_soup = BeautifulSoup(book_page.text, "html.parser")

table = book_soup.select_one("table.table.table-striped")

info = {}
if table:
    for row in table.find_all("tr"):
        key = row.th.text.strip()
        value = row.td.text.strip()
        info[key] = value

desc_tag = book_soup.select_one("#product_description + p")
description = desc_tag.text.strip() if desc_tag else ""

breadcrumb = book_soup.select_one("ul.breadcrumb")
genre = breadcrumb.find_all("li")[2].text.strip() if breadcrumb else ""

In [ ]:
for book in books:

    href = book.h3.a["href"]
    full_url = urljoin(base_url, href)

    book_page = requests.get(full_url, headers=headers)
    book_soup = BeautifulSoup(book_page.text, "html.parser")

In [ ]:
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin

url = "https://books.toscrape.com/catalogue/page-1.html"
base_url = "https://books.toscrape.com/"

headers = {"User-Agent": "Mozilla/5.0"}

response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.text, "html.parser")

books = soup.find_all("article", class_="product_pod")

print(len(books))  # debe dar 20

In [ ]:
for book in books:
    href = book.h3.a["href"]
    full_url = urljoin(base_url, href)

    print(full_url)

In [ ]:
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin

base_url = "https://books.toscrape.com/catalogue/"
data = [https://books.toscrape.com/a-light-in-the-attic_1000/index.html
https://books.toscrape.com/tipping-the-velvet_999/index.html
https://books.toscrape.com/soumission_998/index.html
https://books.toscrape.com/sharp-objects_997/index.html
https://books.toscrape.com/sapiens-a-brief-history-of-humankind_996/index.html
https://books.toscrape.com/the-requiem-red_995/index.html
https://books.toscrape.com/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html
https://books.toscrape.com/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html
https://books.toscrape.com/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html
https://books.toscrape.com/the-black-maria_991/index.html
https://books.toscrape.com/starving-hearts-triangular-trade-trilogy-1_990/index.html
https://books.toscrape.com/shakespeares-sonnets_989/index.html
https://books.toscrape.com/set-me-free_988/index.html
https://books.toscrape.com/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html
https://books.toscrape.com/rip-it-up-and-start-again_986/index.html
https://books.toscrape.com/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html
https://books.toscrape.com/olio_984/index.html
https://books.toscrape.com/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html
https://books.toscrape.com/libertarianism-for-beginners_982/index.html
https://books.toscrape.com/its-only-the-himalayas_981/index.html
]

for link in links:  # <- aquí tu lista de URLs
    response = requests.get(link)
    soup = BeautifulSoup(response.text, "html.parser")

    # tabla de datos
    table = soup.find("table", class_="table table-striped")

    book_info = {}
    if table:
        for row in table.find_all("tr"):
            key = row.th.text
            value = row.td.text
            book_info[key] = value

    # descripción
    desc_tag = soup.find("div", id="product_description")
    description = desc_tag.find_next("p").text if desc_tag else ""

    # género
    breadcrumb = soup.find("ul", class_="breadcrumb")
    genre = breadcrumb.find_all("li")[2].text.strip() if breadcrumb else ""

    data.append({
        "UPC": book_info.get("UPC"),
        "Title": soup.h1.text,
        "Price": book_info.get("Price (incl. tax)"),
        "Rating": soup.find("p", class_="star-rating")["class"][1],
        "Genre": genre,
        "Availability": book_info.get("Availability"),
        "Description": description
    })

df = pd.DataFrame(data)
df

In [ ]:
print(len(links))
print(links[:3])

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from urllib.parse import urljoin

def scrape_books(min_rating, max_price):

    base_url = "https://books.toscrape.com/catalogue/page-{}.html"
    data = []

    rating_map = {
        "One": 1,
        "Two": 2,
        "Three": 3,
        "Four": 4,
        "Five": 5
    }

    for page in range(1, 51):

        response = requests.get(base_url.format(page))
        soup = BeautifulSoup(response.text, "html.parser")

        books = soup.find_all("article", class_="product_pod")

        for book in books:

            title = book.h3.a["title"]
            price = float(book.find("p", class_="price_color").text.replace("£", "").replace("Â", ""))
            rating = rating_map[book.p["class"][1]]

            if price <= max_price and rating >= min_rating:

                link = book.h3.a["href"]
                book_url = urljoin("https://books.toscrape.com/catalogue/", link)

                book_page = requests.get(book_url)
                book_soup = BeautifulSoup(book_page.text, "html.parser")

                # tabla
                table = book_soup.find("table", class_="table table-striped")
                info = {}

                if table:
                    for row in table.find_all("tr"):
                        key = row.th.text
                        value = row.td.text
                        info[key] = value

                # descripción
                desc = book_soup.find("div", id="product_description")
                description = desc.find_next("p").text if desc else ""

                # género
                breadcrumb = book_soup.find("ul", class_="breadcrumb")
                genre = breadcrumb.find_all("li")[2].text.strip() if breadcrumb else ""

                data.append({
                    "UPC": info.get("UPC"),
                    "Title": title,
                    "Price (£)": price,
                    "Rating": rating,
                    "Genre": genre,
                    "Availability": info.get("Availability"),
                    "Description": description
                })

    return pd.DataFrame(data)

In [ ]:
df = scrape_books(4, 20)
df

In [ ]:
print(df.shape)
df.head()

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from urllib.parse import urljoin

In [2]:
def scrape_books(min_rating, max_price):

    base_url = "https://books.toscrape.com/catalogue/page-{}.html"
    data = []

    rating_map = {
        "One": 1,
        "Two": 2,
        "Three": 3,
        "Four": 4,
        "Five": 5
    }

    for page in range(1, 51):

        response = requests.get(base_url.format(page))
        soup = BeautifulSoup(response.text, "html.parser")

        books = soup.find_all("article", class_="product_pod")

        for book in books:

            title = book.h3.a["title"]
            price = float(book.find("p", class_="price_color").text.replace("£", "").replace("Â", ""))
            rating = rating_map[book.p["class"][1]]

            if price <= max_price and rating >= min_rating:

                link = book.h3.a["href"]
                book_url = urljoin("https://books.toscrape.com/catalogue/", link)

                book_page = requests.get(book_url)
                book_soup = BeautifulSoup(book_page.text, "html.parser")

                table = book_soup.find("table", class_="table table-striped")
                info = {}

                if table:
                    for row in table.find_all("tr"):
                        info[row.th.text] = row.td.text

                desc = book_soup.find("div", id="product_description")
                description = desc.find_next("p").text if desc else ""

                breadcrumb = book_soup.find("ul", class_="breadcrumb")
                genre = breadcrumb.find_all("li")[2].text.strip() if breadcrumb else ""

                data.append({
                    "UPC": info.get("UPC"),
                    "Title": title,
                    "Price": price,
                    "Rating": rating,
                    "Genre": genre,
                    "Availability": info.get("Availability"),
                    "Description": description
                })

    return pd.DataFrame(data)

In [3]:
df = scrape_books(4, 20)
df

,UPC,Title,Price,Rating,Genre,Availability,Description
0,ce6396b0f23f6ecc,Set Me Free,17.46,5,Young Adult,In stock (19 available),Aaron Ledbetterâs future had been planned ou...
1,6258a1f6a6dcfe50,The Four Agreements: A Practical Guide to Pers...,17.66,5,Spirituality,In stock (18 available),"In The Four Agreements, don Miguel Ruiz reveal..."
2,6be3beb0793a53e7,Sophie's World,15.94,5,Philosophy,In stock (18 available),A page-turning novel that is also an explorati...
3,657fe5ead67a7767,Untitled Collection: Sabbath Poems 2014,14.27,4,Poetry,In stock (16 available),"More than thirty-five years ago, when the weat..."
4,51653ef291ab7ddc,This One Summer,19.49,4,Sequential Art,In stock (16 available),"Every summer, Rose goes with her mom and dad t..."
...,...,...,...,...,...,...,...
70,9c96cd1329fbd82d,The Zombie Room,19.69,5,Default,In stock (1 available),An unlikely bond is forged between three men f...
71,b78deb463531d078,The Silent Wife,12.34,5,Fiction,In stock (1 available),A chilling psychological thriller about a marr...
72,4280ac3eab57aa5d,The Girl You Lost,12.29,5,Mystery,In stock (1 available),Eighteen years ago your baby daughter was snat...
73,29fc016c459aeb14,The Edge of Reason (Bridget Jones #2),19.18,4,Womens Fiction,In stock (1 available),Monday 27 Januaryâ7:15 a.m. Hurrah! The wild...
74,19fec36a1dfb4c16,A Spy's Devotion (The Regency Spies of London #1),16.97,5,Historical Fiction,In stock (1 available),"In Englandâs Regency era, manners and elegan..."

In [4]:
print(df.shape)

(75, 7)

In [5]:
import requests
from bs4 import BeautifulSoup

url = "https://books.toscrape.com/catalogue/page-1.html"
response = requests.get(url)

print(response.status_code)
print(response.text[:300])

200


<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html l

In [1]:
import requests
from bs4 import BeautifulSoup

url = "https://books.toscrape.com/catalogue/page-1.html"
response = requests.get(url)

print(response.status_code)
print(response.text[:300])

200


<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html l

In [2]:
from bs4 import BeautifulSoup
import requests

url = "https://books.toscrape.com/catalogue/page-1.html"
r = requests.get(url)

soup = BeautifulSoup(r.text, "html.parser")

books = soup.find_all("article", class_="product_pod")

print("Libros encontrados:", len(books))

Libros encontrados: 20

In [3]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

def scrape_books(min_rating, max_price):

    base_url = "https://books.toscrape.com/catalogue/page-{}.html"
    data = []

    rating_map = {"One":1,"Two":2,"Three":3,"Four":4,"Five":5}

    for page in range(1, 51):

        r = requests.get(base_url.format(page))
        soup = BeautifulSoup(r.text, "html.parser")

        books = soup.find_all("article", class_="product_pod")

        for book in books:

            title = book.h3.a["title"]
            price = float(book.find("p", class_="price_color").text.replace("£","").replace("Â",""))
            rating = rating_map[book.p["class"][1]]

            if rating >= min_rating and price <= max_price:

                data.append({
                    "title": title,
                    "price": price,
                    "rating": rating
                })

    return pd.DataFrame(data)

In [4]:
df = scrape_books(4, 20)
df

                                                title  price  rating
0                                         Set Me Free  17.46       5
1   The Four Agreements: A Practical Guide to Pers...  17.66       5
2                                      Sophie's World  15.94       5
3             Untitled Collection: Sabbath Poems 2014  14.27       4
4                                     This One Summer  19.49       4
..                                                ...    ...     ...
70                                    The Zombie Room  19.69       5
71                                    The Silent Wife  12.34       5
72                                  The Girl You Lost  12.29       5
73              The Edge of Reason (Bridget Jones #2)  19.18       4
74  A Spy's Devotion (The Regency Spies of London #1)  16.97       5

[75 rows x 3 columns]

In [5]:
print(len(df))
print(df.head())

75
                                               title  price  rating
0                                        Set Me Free  17.46       5
1  The Four Agreements: A Practical Guide to Pers...  17.66       5
2                                     Sophie's World  15.94       5
3            Untitled Collection: Sabbath Poems 2014  14.27       4
4                                    This One Summer  19.49       4

In [6]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from urllib.parse import urljoin

def scrape_books(min_rating, max_price):

    base_url = "https://books.toscrape.com/catalogue/page-{}.html"
    data = []

    rating_map = {"One":1,"Two":2,"Three":3,"Four":4,"Five":5}

    for page in range(1, 51):

        r = requests.get(base_url.format(page))
        soup = BeautifulSoup(r.text, "html.parser")

        books = soup.find_all("article", class_="product_pod")

        for book in books:

            title = book.h3.a["title"]
            price = float(book.find("p", class_="price_color").text.replace("£","").replace("Â",""))
            rating = rating_map[book.p["class"][1]]

            if rating >= min_rating and price <= max_price:

                link = book.h3.a["href"]
                book_url = urljoin("https://books.toscrape.com/catalogue/", link)

                page = requests.get(book_url)
                soup_book = BeautifulSoup(page.text, "html.parser")

                table = soup_book.find("table", class_="table table-striped")
                info = {}

                if table:
                    for row in table.find_all("tr"):
                        info[row.th.text] = row.td.text

                desc = soup_book.find("div", id="product_description")
                description = desc.find_next("p").text if desc else ""

                breadcrumb = soup_book.find("ul", class_="breadcrumb")
                genre = breadcrumb.find_all("li")[2].text.strip() if breadcrumb else ""

                data.append({
                    "UPC": info.get("UPC"),
                    "Title": title,
                    "Price": price,
                    "Rating": rating,
                    "Genre": genre,
                    "Availability": info.get("Availability"),
                    "Description": description
                })

    return pd.DataFrame(data)

In [7]:
df = scrape_books(4, 20)
df.head()

,UPC,Title,Price,Rating,Genre,Availability,Description
0,ce6396b0f23f6ecc,Set Me Free,17.46,5,Young Adult,In stock (19 available),Aaron Ledbetterâs future had been planned ou...
1,6258a1f6a6dcfe50,The Four Agreements: A Practical Guide to Pers...,17.66,5,Spirituality,In stock (18 available),"In The Four Agreements, don Miguel Ruiz reveal..."
2,6be3beb0793a53e7,Sophie's World,15.94,5,Philosophy,In stock (18 available),A page-turning novel that is also an explorati...
3,657fe5ead67a7767,Untitled Collection: Sabbath Poems 2014,14.27,4,Poetry,In stock (16 available),"More than thirty-five years ago, when the weat..."
4,51653ef291ab7ddc,This One Summer,19.49,4,Sequential Art,In stock (16 available),"Every summer, Rose goes with her mom and dad t..."

In [8]:
print(df.shape)
print(df.columns)

(75, 7)
Index(['UPC', 'Title', 'Price', 'Rating', 'Genre', 'Availability',
       'Description'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 75 entries, 0 to 74
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   UPC           75 non-null     object
 1   Title         75 non-null     object
 2   Price         75 non-null     float64
 3   Rating        75 non-null     int64
 4   Genre         75 non-null     object
 5   Availability  75 non-null     object
 6   Description   75 non-null     object
dtypes: float64(1), int64(1), object(5)
memory usage: 4.2+ KB

In [10]:
df.head()

,UPC,Title,Price,Rating,Genre,Availability,Description
0,ce6396b0f23f6ecc,Set Me Free,17.46,5,Young Adult,In stock (19 available),Aaron Ledbetterâs future had been planned ou...
1,6258a1f6a6dcfe50,The Four Agreements: A Practical Guide to Pers...,17.66,5,Spirituality,In stock (18 available),"In The Four Agreements, don Miguel Ruiz reveal..."
2,6be3beb0793a53e7,Sophie's World,15.94,5,Philosophy,In stock (18 available),A page-turning novel that is also an explorati...
3,657fe5ead67a7767,Untitled Collection: Sabbath Poems 2014,14.27,4,Poetry,In stock (16 available),"More than thirty-five years ago, when the weat..."
4,51653ef291ab7ddc,This One Summer,19.49,4,Sequential Art,In stock (16 available),"Every summer, Rose goes with her mom and dad t..."

In [11]:
df.sort_values("Rating", ascending=False).head()

,UPC,Title,Price,Rating,Genre,Availability,Description
0,ce6396b0f23f6ecc,Set Me Free,17.46,5,Young Adult,In stock (19 available),Aaron Ledbetterâs future had been planned ou...
28,94a958ea126cdcd5,Dear Mr. Knightley,11.21,5,Fiction,In stock (14 available),Dear Mr. Knightley is a contemporary epistolar...
33,28b2df9fadc9f07e,"Mother, Can You Not?",16.89,5,Nonfiction,In stock (11 available),Based on the wildly popular Instagram account ...
34,40c4bf520c17de54,A Gentleman's Position (Society of Gentlemen #3),14.75,5,Romance,In stock (11 available),"Power, privilege, and the rigid rules of class..."
1,6258a1f6a6dcfe50,The Four Agreements: A Practical Guide to Pers...,17.66,5,Spirituality,In stock (18 available),"In The Four Agreements, don Miguel Ruiz reveal..."

In [12]:
df[(df["Rating"] >= 4) & (df["Price"] <= 20)].shape

(75, 7)