# Lab | Web Scraping

Welcome to the "Books to Scrape" Web Scraping Adventure Lab!

**Objective**

In this lab, we will embark on a mission to unearth valuable insights from the data available on Books to Scrape, an online platform showcasing a wide variety of books. As data analyst, you have been tasked with scraping a specific subset of book data from Books to Scrape to assist publishing companies in understanding the landscape of highly-rated books across different genres. Your insights will help shape future book marketing strategies and publishing decisions.

**Background**

In a world where data has become the new currency, businesses are leveraging big data to make informed decisions that drive success and profitability. The publishing industry, much like others, utilizes data analytics to understand market trends, reader preferences, and the performance of books based on factors such as genre, author, and ratings. Books to Scrape serves as a rich source of such data, offering detailed information about a diverse range of books, making it an ideal platform for extracting insights to aid in informed decision-making within the literary world.

**Task**

Your task is to create a Python script using BeautifulSoup and pandas to scrape Books to Scrape book data, focusing on book ratings and genres. The script should be able to filter books with ratings above a certain threshold and in specific genres. Additionally, the script should structure the scraped data in a tabular format using pandas for further analysis.

**Expected Outcome**

A function named `scrape_books` that takes two parameters: `min_rating` and `max_price`. The function should scrape book data from the "Books to Scrape" website and return a `pandas` DataFrame with the following columns:

**Expected Outcome**

- A function named `scrape_books` that takes two parameters: `min_rating` and `max_price`.
- The function should return a DataFrame with the following columns:
  - **UPC**: The Universal Product Code (UPC) of the book.
  - **Title**: The title of the book.
  - **Price (£)**: The price of the book in pounds.
  - **Rating**: The rating of the book (1-5 stars).
  - **Genre**: The genre of the book.
  - **Availability**: Whether the book is in stock or not.
  - **Description**: A brief description or product description of the book (if available).
  
You will execute this script to scrape data for books with a minimum rating of `4.0 and above` and a maximum price of `£20`. 

Remember to experiment with different ratings and prices to ensure your code is versatile and can handle various searches effectively!

**Resources**

- [Beautiful Soup Documentation](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)
- [Pandas Documentation](https://pandas.pydata.org/pandas-docs/stable/index.html)
- [Books to Scrape](https://books.toscrape.com/)

**Hint**

Your first mission is to familiarize yourself with the **Books to Scrape** website. Navigate to [Books to Scrape](http://books.toscrape.com/) and explore the available books to understand their layout and structure. 

Next, think about how you can set parameters for your data extraction:

- **Minimum Rating**: Focus on books with a rating of 4.0 and above.
- **Maximum Price**: Filter for books priced up to £20.

After reviewing the site, you can construct a plan for scraping relevant data. Pay attention to the details displayed for each book, including the title, price, rating, and availability. This will help you identify the correct HTML elements to target with your scraping script.

Make sure to build your scraping URL and logic based on the patterns you observe in the HTML structure of the book listings!


---

**Best of luck! Immerse yourself in the world of books, and may the data be with you!**

**Important Note**:

In the fast-changing online world, websites often update and change their structures. When you try this lab, the **Books to Scrape** website might differ from what you expect.

If you encounter issues due to these changes, like new rules or obstacles preventing data extraction, don’t worry! Get creative.

You can choose another website that interests you and is suitable for scraping data. Options like Wikipedia, The New York Times, or even library databases are great alternatives. The main goal remains the same: extract useful data and enhance your web scraping skills while exploring a source of information you enjoy. This is your opportunity to practice and adapt to different web environments!

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
url = "http://books.toscrape.com/"
response = requests.get(url)

soup = BeautifulSoup(response.text, "html.parser")

In [3]:
soup.title

<title>
    All products | Books to Scrape - Sandbox
</title>

Each book on the page is stored inside an HTML element with the class product_pod.
We extract all these elements to work with individual book data.

In [4]:
books = soup.find_all("article", class_="product_pod")

In [5]:
len(books)

20

The title of each book is stored in the title attribute of the <a> tag inside the <h3> element.

In [6]:
books[0]

<article class="product_pod">
<div class="image_container">
<a href="catalogue/a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
<div class="product_price">
<p class="price_color">Â£51.77</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>

In [7]:
books[0].h3.a["title"]

'A Light in the Attic'

Extracting Book Prices

The price of each book is stored inside a <p> tag with the class price_color.
We extract the text and later convert it into a numeric format.

In [8]:
books[0].find("p", class_="price_color").text

'Â£51.77'

In [9]:
prices = [book.find("p", class_="price_color").text for book in books]

In [10]:
prices[:5]

['Â£51.77', 'Â£53.74', 'Â£50.10', 'Â£47.82', 'Â£54.23']

## Cleaning Book Prices

The extracted prices are stored as text and include a currency symbol with an encoding issue.  
We remove the unwanted characters and convert the values into floats so they can be filtered numerically.

In [11]:
clean_prices = [price.replace("Â£", "").replace("£", "") for price in prices]

clean_prices[:5]

['51.77', '53.74', '50.10', '47.82', '54.23']

In [12]:
numeric_prices = [float(price) for price in clean_prices]

numeric_prices[:5]

[51.77, 53.74, 50.1, 47.82, 54.23]

Extracting Book Ratings

The rating is stored in the class attribute of a <p> tag.
Each book has a class like star-rating Three, where the second class represents the rating.

In [13]:
books[0].find("p", class_="star-rating")["class"]

['star-rating', 'Three']

In [14]:
ratings = [book.find("p", class_="star-rating")["class"][1] for book in books]

ratings[:5]

['Three', 'One', 'One', 'Four', 'Five']

In [ ]:
## Converting Ratings to Numeric Values

The ratings are currently stored as text (e.g. "One", "Two", "Three").  
We map these values to integers so they can be used for filtering.

In [15]:
rating_map = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

numeric_ratings = [rating_map[rating] for rating in ratings]

numeric_ratings[:5]

[3, 1, 1, 4, 5]

Extracting Availability

Availability information is stored as text inside a <p> tag with the class instock availability.

In [16]:
availability = [book.find("p", class_="instock availability").text.strip() for book in books]

availability[:5]

['In stock', 'In stock', 'In stock', 'In stock', 'In stock']

In [18]:
titles = [book.h3.a["title"] for book in books]

titles[:5]

['A Light in the Attic',
 'Tipping the Velvet',
 'Soumission',
 'Sharp Objects',
 'Sapiens: A Brief History of Humankind']

## Creating the DataFrame

After extracting titles, prices, ratings, and availability, we combine the lists into a structured pandas DataFrame for further filtering and analysis.

In [19]:
books_df = pd.DataFrame({
    "title": titles,
    "price": numeric_prices,
    "rating": numeric_ratings,
    "availability": availability
})

books_df.head()

                                   title  price  rating availability
0                   A Light in the Attic  51.77       3     In stock
1                     Tipping the Velvet  53.74       1     In stock
2                             Soumission  50.10       1     In stock
3                          Sharp Objects  47.82       4     In stock
4  Sapiens: A Brief History of Humankind  54.23       5     In stock

In [20]:
books_df.shape

(20, 4)

In [21]:
books_df.dtypes

title               str
price           float64
rating            int64
availability        str
dtype: object

## Filtering the Scraped Books

We keep only books that meet both conditions:
- rating greater than or equal to the minimum rating
- price lower than or equal to the maximum price

In [22]:
filtered_books = books_df[
    (books_df["rating"] >= 4) &
    (books_df["price"] <= 20)
]

filtered_books.head()

          title  price  rating availability
12  Set Me Free  17.46       5     In stock

In [23]:
filtered_books.shape

(1, 4)

In [24]:
filtered_books["rating"].min()

np.int64(5)

In [25]:
filtered_books["price"].max()

np.float64(17.46)

## Building the Scraping Function

To make the scraper reusable, we wrap the scraping and filtering logic into a function.

The function takes:
- `min_rating`: the minimum rating a book must have
- `max_price`: the maximum price a book can have

It returns a filtered pandas DataFrame.

In [27]:
def scrape_books(min_rating, max_price):
    import requests
    from bs4 import BeautifulSoup
    import pandas as pd

    url = "http://books.toscrape.com/"
    response = requests.get(url)
    soup = BeautifulSoup(response.text, "html.parser")

    books = soup.find_all("article", class_="product_pod")

    titles = [book.h3.a["title"] for book in books]

    prices = [book.find("p", class_="price_color").text for book in books]
    clean_prices = [price.replace("Â£", "").replace("£", "") for price in prices]
    numeric_prices = [float(price) for price in clean_prices]

    ratings = [book.find("p", class_="star-rating")["class"][1] for book in books]
    rating_map = {
        "One": 1,
        "Two": 2,
        "Three": 3,
        "Four": 4,
        "Five": 5
    }
    numeric_ratings = [rating_map[rating] for rating in ratings]

    availability = [
        book.find("p", class_="instock availability").text.strip()
        for book in books
    ]

    books_df = pd.DataFrame({
        "title": titles,
        "price": numeric_prices,
        "rating": numeric_ratings,
        "availability": availability
    })

    filtered_books = books_df[
        (books_df["rating"] >= min_rating) &
        (books_df["price"] <= max_price)
    ]

    return filtered_books

In [28]:
scraped_books = scrape_books(min_rating=4, max_price=20)

scraped_books

          title  price  rating availability
12  Set Me Free  17.46       5     In stock

In [29]:
scraped_books.shape

(1, 4)

In [30]:
scraped_books["rating"].min()

np.int64(5)

In [31]:
scraped_books["price"].max()

np.float64(17.46)

In [32]:
books[0].h3.a["href"]

'catalogue/a-light-in-the-attic_1000/index.html'

In [33]:
base_url = "http://books.toscrape.com/"

book_url = base_url + books[0].h3.a["href"]

book_url

'http://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html'

In [34]:
response = requests.get(book_url)
soup_detail = BeautifulSoup(response.text, "html.parser")

soup_detail

<!DOCTYPE html>

<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-us"> <!--<![endif]-->
<head>
<title>
    A Light in the Attic | Books to Scrape - Sandbox
</title>
<meta content="text/html; charset=utf-8" http-equiv="content-type"/>
<meta content="24th Jun 2016 09:29" name="created"/>
<meta content="
    It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love th It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love that Silverstein. Need proof of his genius? RockabyeRockabye baby, in the treetopDon't you know a treetopIs no safe place to rock?And who put you up there,And your cradle, too?Baby, I think someone down here'sGot it in for you. Shel, you never sounded so good. ...more
" name="description"/>
<meta content="width=device-width" name="viewport"/>
<meta content="NOARCHIVE,NOCACHE" name="robots"/>
<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
<link href="../../static/oscar/favicon.ico" rel="shortcut icon"/>
<link href="../../static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>
<link href="../../static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>
<link href="../../static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>
</head>
<body class="default" id="default">
<header class="header container-fluid">
<div class="page_inner">
<div class="row">
<div class="col-sm-8 h1"><a href="../../index.html">Books to Scrape</a><small> We love being scraped!</small>
</div>
</div>
</div>
</header>
<div class="container-fluid page">
<div class="page_inner">
<ul class="breadcrumb">
<li>
<a href="../../index.html">Home</a>
</li>
<li>
<a href="../category/books_1/index.html">Books</a>
</li>
<li>
<a href="../category/books/poetry_23/index.html">Poetry</a>
</li>
<li class="active">A Light in the Attic</li>
</ul>
<div id="messages">
</div>
<div class="content">
<div id="promotions">
</div>
<div id="content_inner">
<article class="product_page"><!-- Start of product page -->
<div class="row">
<div class="col-sm-6">
<div class="carousel" id="product_gallery">
<div class="thumbnail">
<div class="carousel-inner">
<div class="item active">
<img alt="A Light in the Attic" src="../../media/cache/fe/72/fe72f0532301ec28892ae79a629a293c.jpg"/>
</div>
</div>
</div>
</div>
</div>
<div class="col-sm-6 product_main">
<h1>A Light in the Attic</h1>
<p class="price_color">Â£51.77</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock (22 available)

</p>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<!-- <small><a href="/catalogue/a-light-in-the-attic_1000/reviews/">


                    0 customer reviews

        </a></small>
         -->


<!--
    <a id="write_review" href="/catalogue/a-light-in-the-attic_1000/reviews/add/#addreview" class="btn btn-success btn-sm">
        Write a review
    </a>

 --></p>
<hr/>
<div class="alert alert-warning" role="alert"><strong>Warning!</strong> This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.</div>
</div><!-- /col-sm-6 -->
</div><!-- /row -->
<div class="sub-header" id="product_description">
<h2>Product Description</h2>
</div>
<p>It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love th It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love that Silverstein. Need proof of his genius? RockabyeRockabye baby, in the treetopDon't you know a treetopIs no safe place to rock?And who put you up there,And your cradle, too?Baby, I think someone down here'sGot it in for you. Shel, you never sounded so good. ...more</p>
<div class="sub-header">
<h2>Product Information</h2>
</div>
<table class="table table-striped">
<tr>
<th>UPC</th><td>a897fe39b1053632</td>
</tr>
<tr>
<th>Product Type</th><td>Books</td>
</tr>
<tr>
<th>Price (excl. tax)</th><td>Â£51.77</td>
</tr>
<tr>
<th>Price (incl. tax)</th><td>Â£51.77</td>
</tr>
<tr>
<th>Tax</th><td>Â£0.00</td>
</tr>
<tr>
<th>Availability</th>
<td>In stock (22 available)</td>
</tr>
<tr>
<th>Number of reviews</th>
<td>0</td>
</tr>
</table>
<section>
<div class="sub-header" id="reviews">
</div>
</section>
</article><!-- End of product page -->
</div>
</div>
</div>
</div>
<footer class="footer container-fluid">
</footer>
<!-- jQuery -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../static/oscar/js/jquery/jquery-1.9.1.min.js"><\/script>')</script>
<!-- Twitter Bootstrap -->
<script src="../../static/oscar/js/bootstrap3/bootstrap.min.js" type="text/javascript"></script>
<!-- Oscar -->
<script charset="utf-8" src="../../static/oscar/js/oscar/ui.js" type="text/javascript"></script>
<script charset="utf-8" src="../../static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.js" type="text/javascript"></script>
<script charset="utf-8" src="../../static/oscar/js/bootstrap-datetimepicker/locales/bootstrap-datetimepicker.all.js" type="text/javascript"></script>
<script type="text/javascript">
            $(function() {


    oscar.init();

            });
        </script>
<!-- Version: N/A -->
</body>
</html>

In [35]:
soup_detail.find("table").find("td").text

'a897fe39b1053632'

In [36]:
soup_detail.find("ul", class_="breadcrumb").find_all("li")[2].text.strip()

'Poetry'

In [37]:
soup_detail.find("meta", attrs={"name": "description"})["content"].strip()

"It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love th It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love that Silverstein. Need proof of his genius? RockabyeRockabye baby, in the treetopDon't you know a treetopIs no safe place to rock?And who put you up there,And your cradle, too?Baby, I think someone down here'sGot it in for you. Shel, you never sounded so good. ...more"

In [38]:
soup_detail.find("table").find("td").text

'a897fe39b1053632'

In [39]:
soup_detail.find("ul", class_="breadcrumb").find_all("li")[2].text.strip()

'Poetry'

In [40]:
soup_detail.find("meta", attrs={"name": "description"})["content"].strip()

"It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love th It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love that Silverstein. Need proof of his genius? RockabyeRockabye baby, in the treetopDon't you know a treetopIs no safe place to rock?And who put you up there,And your cradle, too?Baby, I think someone down here'sGot it in for you. Shel, you never sounded so good. ...more"

## Extracting Additional Book Details

To enrich the dataset, we visit each book's detail page and extract:
- UPC (unique product code)
- genre
- description

This requires making an additional request per book.

In [41]:
base_url = "http://books.toscrape.com/"

upc_list = []
genre_list = []
description_list = []

for book in books:
    relative_url = book.h3.a["href"]
    book_url = base_url + relative_url

    response = requests.get(book_url)
    soup_detail = BeautifulSoup(response.text, "html.parser")

    # UPC
    upc = soup_detail.find("table").find("td").text
    upc_list.append(upc)

    # Genre
    genre = soup_detail.find("ul", class_="breadcrumb").find_all("li")[2].text.strip()
    genre_list.append(genre)

    # Description
    description = soup_detail.find("meta", attrs={"name": "description"})["content"].strip()
    description_list.append(description)

In [42]:
len(upc_list), len(genre_list), len(description_list)

(20, 20, 20)

In [43]:
books_df = pd.DataFrame({
    "title": titles,
    "price": numeric_prices,
    "rating": numeric_ratings,
    "availability": availability,
    "upc": upc_list,
    "genre": genre_list,
    "description": description_list
})

books_df.head()

,title,price,rating,availability,upc,genre,description
0,A Light in the Attic,51.77,3,In stock,a897fe39b1053632,Poetry,It's hard to imagine a world without A Light i...
1,Tipping the Velvet,53.74,1,In stock,90fa61229261140a,Historical Fiction,"""Erotic and absorbing...Written with starling ..."
2,Soumission,50.10,1,In stock,6957f44c3847a760,Fiction,"Dans une France assez proche de la nÃ´tre, un ..."
3,Sharp Objects,47.82,4,In stock,e00eb4fd7b871a48,Mystery,"WICKED above her hipbone, GIRL across her hear..."
4,Sapiens: A Brief History of Humankind,54.23,5,In stock,4165285e1663650f,History,From a renowned historian comes a groundbreaki...

## Final Scraping Function

The final function scrapes both the book listing page and each individual book detail page.

It returns a filtered DataFrame containing:
- title
- price
- rating
- availability
- upc
- genre
- description

In [44]:
def scrape_books(min_rating, max_price):
    import requests
    from bs4 import BeautifulSoup
    import pandas as pd

    base_url = "http://books.toscrape.com/"
    response = requests.get(base_url)
    soup = BeautifulSoup(response.text, "html.parser")

    books = soup.find_all("article", class_="product_pod")

    titles = []
    prices = []
    ratings = []
    availability_list = []
    upc_list = []
    genre_list = []
    description_list = []

    rating_map = {
        "One": 1,
        "Two": 2,
        "Three": 3,
        "Four": 4,
        "Five": 5
    }

    for book in books:
        # title
        title = book.h3.a["title"]
        titles.append(title)

        # price
        raw_price = book.find("p", class_="price_color").text
        clean_price = raw_price.replace("Â£", "").replace("£", "")
        numeric_price = float(clean_price)
        prices.append(numeric_price)

        # rating
        raw_rating = book.find("p", class_="star-rating")["class"][1]
        numeric_rating = rating_map[raw_rating]
        ratings.append(numeric_rating)

        # availability
        availability = book.find("p", class_="instock availability").text.strip()
        availability_list.append(availability)

        # detail page
        relative_url = book.h3.a["href"]
        book_url = base_url + relative_url

        detail_response = requests.get(book_url)
        detail_soup = BeautifulSoup(detail_response.text, "html.parser")

        # upc
        upc = detail_soup.find("table").find("td").text
        upc_list.append(upc)

        # genre
        genre = detail_soup.find("ul", class_="breadcrumb").find_all("li")[2].text.strip()
        genre_list.append(genre)

        # description
        description = detail_soup.find("meta", attrs={"name": "description"})["content"].strip()
        description_list.append(description)

    books_df = pd.DataFrame({
        "title": titles,
        "price": prices,
        "rating": ratings,
        "availability": availability_list,
        "upc": upc_list,
        "genre": genre_list,
        "description": description_list
    })

    filtered_books = books_df[
        (books_df["rating"] >= min_rating) &
        (books_df["price"] <= max_price)
    ]

    return filtered_books

In [45]:
scraped_books = scrape_books(min_rating=4, max_price=20)

scraped_books

,title,price,rating,availability,upc,genre,description
12,Set Me Free,17.46,5,In stock,ce6396b0f23f6ecc,Young Adult,Aaron Ledbetterâs future had been planned ou...

In [46]:
scraped_books.shape

(1, 7)

In [47]:
scraped_books["rating"].min()

np.int64(5)

In [48]:
scraped_books["price"].max()

np.float64(17.46)

In [49]:
scraped_books.columns

Index(['title', 'price', 'rating', 'availability', 'upc', 'genre',
       'description'],
      dtype='str')