# Lab | Web Scraping

Welcome to the "Books to Scrape" Web Scraping Adventure Lab!

**Objective**

In this lab, we will embark on a mission to unearth valuable insights from the data available on Books to Scrape, an online platform showcasing a wide variety of books. As data analyst, you have been tasked with scraping a specific subset of book data from Books to Scrape to assist publishing companies in understanding the landscape of highly-rated books across different genres. Your insights will help shape future book marketing strategies and publishing decisions.

**Background**

In a world where data has become the new currency, businesses are leveraging big data to make informed decisions that drive success and profitability. The publishing industry, much like others, utilizes data analytics to understand market trends, reader preferences, and the performance of books based on factors such as genre, author, and ratings. Books to Scrape serves as a rich source of such data, offering detailed information about a diverse range of books, making it an ideal platform for extracting insights to aid in informed decision-making within the literary world.

**Task**

Your task is to create a Python script using BeautifulSoup and pandas to scrape Books to Scrape book data, focusing on book ratings and genres. The script should be able to filter books with ratings above a certain threshold and in specific genres. Additionally, the script should structure the scraped data in a tabular format using pandas for further analysis.

**Expected Outcome**

A function named `scrape_books` that takes two parameters: `min_rating` and `max_price`. The function should scrape book data from the "Books to Scrape" website and return a `pandas` DataFrame with the following columns:

**Expected Outcome**

- A function named `scrape_books` that takes two parameters: `min_rating` and `max_price`.
- The function should return a DataFrame with the following columns:
  - **UPC**: The Universal Product Code (UPC) of the book.
  - **Title**: The title of the book.
  - **Price (£)**: The price of the book in pounds.
  - **Rating**: The rating of the book (1-5 stars).
  - **Genre**: The genre of the book.
  - **Availability**: Whether the book is in stock or not.
  - **Description**: A brief description or product description of the book (if available).
  
You will execute this script to scrape data for books with a minimum rating of `4.0 and above` and a maximum price of `£20`. 

Remember to experiment with different ratings and prices to ensure your code is versatile and can handle various searches effectively!

**Resources**

- [Beautiful Soup Documentation](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)
- [Pandas Documentation](https://pandas.pydata.org/pandas-docs/stable/index.html)
- [Books to Scrape](https://books.toscrape.com/)

**Hint**

Your first mission is to familiarize yourself with the **Books to Scrape** website. Navigate to [Books to Scrape](http://books.toscrape.com/) and explore the available books to understand their layout and structure. 

Next, think about how you can set parameters for your data extraction:

- **Minimum Rating**: Focus on books with a rating of 4.0 and above.
- **Maximum Price**: Filter for books priced up to £20.

After reviewing the site, you can construct a plan for scraping relevant data. Pay attention to the details displayed for each book, including the title, price, rating, and availability. This will help you identify the correct HTML elements to target with your scraping script.

Make sure to build your scraping URL and logic based on the patterns you observe in the HTML structure of the book listings!


---

**Best of luck! Immerse yourself in the world of books, and may the data be with you!**

**Important Note**:

In the fast-changing online world, websites often update and change their structures. When you try this lab, the **Books to Scrape** website might differ from what you expect.

If you encounter issues due to these changes, like new rules or obstacles preventing data extraction, don’t worry! Get creative.

You can choose another website that interests you and is suitable for scraping data. Options like Wikipedia, The New York Times, or even library databases are great alternatives. The main goal remains the same: extract useful data and enhance your web scraping skills while exploring a source of information you enjoy. This is your opportunity to practice and adapt to different web environments!

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
BASE_URL = "https://books.toscrape.com/"

RATING_MAP = {"One": 1,"Two": 2,"Three": 3,"Four": 4,"Five": 5}

In [6]:

def scrape_books(min_rating=4, max_price=20):
    books_data = []
    page_url = "catalogue/page-1.html"

    while page_url:
        response = requests.get(BASE_URL + page_url)
        soup = BeautifulSoup(response.text, "html.parser")

        books = soup.select("article.product_pod")

        for book in books:
            # --- Rating ---
            rating_class = book.select_one("p.star-rating")["class"]
            rating_word = rating_class[1]
            rating = RATING_MAP.get(rating_word, 0)

            # --- Price ---
            price_text = book.select_one("p.price_color").text
            price = float(price_text.replace("£", "").replace("Â", ""))


            # --- Filters ---
            if rating < min_rating or price > max_price:
                continue

            # --- Book detail page ---
            book_link = book.find("h3").find("a")["href"]
            book_url = BASE_URL + "catalogue/" + book_link.replace("../", "")
            book_response = requests.get(book_url)
            book_soup = BeautifulSoup(book_response.text, "html.parser")

            # --- Title ---
            title = book_soup.find("h1").text

            # --- Product information table ---
            table = book_soup.select_one("table.table.table-striped")
            rows = table.find_all("tr")
            product_info = {
                row.find("th").text: row.find("td").text
                for row in rows
            }

            upc = product_info.get("UPC")
            availability = product_info.get("Availability")

            # --- Genre ---
            genre = book_soup.select("ul.breadcrumb li a")[2].text

            # --- Description ---
            description_tag = book_soup.select_one("#product_description ~ p")
            description = description_tag.text if description_tag else None

            books_data.append({
                "UPC": upc,
                "Title": title,
                "Price (£)": price,
                "Rating": rating,
                "Genre": genre,
                "Availability": availability,
                "Description": description
            })

        # --- Pagination ---
        next_button = soup.select_one("li.next a")
        page_url = next_button["href"] if next_button else None

    return pd.DataFrame(books_data)

In [8]:
scrape_books(max_price = 30)

,UPC,Title,Price (£),Rating,Genre,Availability,Description
0,e10e1e165dc8be4a,The Boys in the Boat: Nine Americans and Their...,22.60,4,Default,In stock (19 available),For readers of Laura Hillenbrand's Seabiscuit ...
1,30a7f60cd76ca58c,Shakespeare's Sonnets,20.66,4,Poetry,In stock (19 available),This book is an important and complete collect...
2,ce6396b0f23f6ecc,Set Me Free,17.46,5,Young Adult,In stock (19 available),Aaron Ledbetterâs future had been planned ou...

In [9]:
scrape_books(max_price = 60)

,UPC,Title,Price (£),Rating,Genre,Availability,Description
0,e00eb4fd7b871a48,Sharp Objects,47.82,4,Mystery,In stock (20 available),"WICKED above her hipbone, GIRL across her hear..."
1,4165285e1663650f,Sapiens: A Brief History of Humankind,54.23,5,History,In stock (20 available),From a renowned historian comes a groundbreaki...
2,2597b5a345f45e1b,The Dirty Little Secrets of Getting Your Dream...,33.34,4,Business,In stock (19 available),Drawing on his extensive experience evaluating...
3,e10e1e165dc8be4a,The Boys in the Boat: Nine Americans and Their...,22.60,4,Default,In stock (19 available),For readers of Laura Hillenbrand's Seabiscuit ...
4,30a7f60cd76ca58c,Shakespeare's Sonnets,20.66,4,Poetry,In stock (19 available),This book is an important and complete collect...
5,ce6396b0f23f6ecc,Set Me Free,17.46,5,Young Adult,In stock (19 available),Aaron Ledbetterâs future had been planned ou...
6,3b1c02bac2a429e6,Scott Pilgrim's Precious Little Life (Scott Pi...,52.29,5,Sequential Art,In stock (19 available),Scott Pilgrim's life is totally sweet. He's 23...
7,a34ba96d4081e6a4,Rip it Up and Start Again,35.02,5,Music,In stock (19 available),"Punk's raw power rejuvenated rock, but by the ..."

In [10]:
scrape_books(max_price = 30, min_rating = 3)

,UPC,Title,Price (£),Rating,Genre,Availability,Description
0,e72a5dfc7e9267b2,The Coming Woman: A Novel Based on the Life of...,17.93,3,Default,In stock (19 available),"""If you have a heart, if you have a soul, Kare..."
1,e10e1e165dc8be4a,The Boys in the Boat: Nine Americans and Their...,22.60,4,Default,In stock (19 available),For readers of Laura Hillenbrand's Seabiscuit ...
2,30a7f60cd76ca58c,Shakespeare's Sonnets,20.66,4,Poetry,In stock (19 available),This book is an important and complete collect...
3,ce6396b0f23f6ecc,Set Me Free,17.46,5,Young Adult,In stock (19 available),Aaron Ledbetterâs future had been planned ou...